apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-template.fullname" . }}-auth-server
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.authServer.port }}
      targetPort: {{ .Values.authServer.targetPort }}
      nodePort: {{ .Values.authServer.nodePort }}
  selector:
      {{- include "application-template.selectorLabels" . | nindent 4 }}
