apiVersion: v2
name: @project.artifactId@-chart
description: A Helm chart for Spring 6 Project 
type: application
version: @helm.chart.version@ 
appVersion: @helm.chart.version@

dependencies:
  - name: spring-6-reactive-mongo-mongodb-chart
    version: @helm.chart.version@
    repository: file://charts/mongodb
    alias: mongodb
    condition: mongodb.enabled
