apiVersion: v2
name: @project.artifactId@
description: A Helm chart for Spring 6 Project 
type: application
version: @helm.chart.version@ 
appVersion: @project.version@

dependencies:
  - name: spring-6-reactive-mongo-mongodb
    version: @helm.chart.version@
    repository: file://charts/spring-6-reactive-mongo-mongodb
    condition: mongodb.enabled
  - name: spring-6-auth-server
    version: "v0.0.4-SNAPSHOT"
    repository: "oci://registry-1.docker.io/domboeckli"
    condition: authServer.enabled  
