replicaCount: 1

image:
  repository: domboeckli/@project.artifactId@
  tag: @project.version@

# Namespace configuration
# This defines the Kubernetes namespace where the resources will be deployed
deployment:
  namespace: spring-6-reactive-mongo

service:
  type: NodePort
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false

spring:
  profiles:
    active: local

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    
  mongodb:
    port: 2222
