apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "secret"
