apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    {{- include "application-template.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
    - protocol: TCP
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.targetPort }}
      nodePort: {{ .Values.mongodb.nodePort }}
  type: NodePort
