spring:
  application:
    name: spring-6-reactive-mongo
  
  data:
    mongodb:
      # uri will be changed to the exposed port when the docker/testcontainer has been started
      uri: mongodb://localhost:27017/sfg
      database: sfg
