apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-spring-mongodb-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: "root"
  SPRING_DATA_MONGODB_PASSWORD: "secret"
