apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-mongodb-secrets
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATA_MONGODB_USERNAME: "root"
  SPRING_DATA_MONGODB_PASSWORD: "secret"

  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "secret"
