apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-template.fullname" . }}-mysql-secrets
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "application-template.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}

  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ADMIN_USER: {{ .Values.mysql.adminUser | quote }}
  MYSQL_ADMIN_PASSWORD: {{ .Values.mysql.adminPassword | quote }}

  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.user | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.password | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.mysql.adminUser | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.mysql.adminPassword | quote }}
  SPRING_FLYWAY_USER: {{ .Values.mysql.adminUser | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.mysql.adminPassword | quote }}
